name: Build Logseq Modules

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout logseq-modules
      uses: actions/checkout@v4

    - name: Fetch config.edn
      run: |
        mkdir -p build/logseq
        curl -o build/logseq/config.edn https://raw.githubusercontent.com/logseq/logseq/master/src/resources/templates/config.edn

    - name: Install logseq-modules
      run: |
        python3 install.py --color --diff --apply build/logseq

    - name: Store result
      uses: actions/upload-artifact@v4
      with:
        name: logseq-modules-${{ github.ref_name }}
        path: build
        if-no-files-found: error
